import os

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
CORREO_ORIGEN = os.getenv("CORREO_ORIGEN")
CORREO_DESTINO = os.getenv("CORREO_DESTINO")
CORREO_REPORTE_DESTINO = os.getenv("CORREO_REPORTE_DESTINO")
ETIQUETA_GMAIL = os.getenv("ETIQUETA_GMAIL")
LIMITE_CORREOS_TEST = int(os.getenv("LIMITE_CORREOS_TEST", "100"))
GMAIL_PASSWORD = os.getenv("GMAIL_PASSWORD")